signin page
stamford-syntax-club/course-compose pull request #51
Opened 2024-03-13 08:15 UTC by Ayham1590

sign in and sign up page UI

2024-03-13 16:05 UTC, CryoMilo requested changes

2024-03-13 16:05 UTC, CryoMilo commented on apps/web/app/signin/page.tsx
Hi bro @Ayham1590 

- We would need a signup page and a link to access to it. 
- We would need a Login button too.

![Screenshot 2024-03-13 at 11 01 52 PM](https://github.com/stamford-syntax-club/course-compose/assets/69119911/34e142f8-4c8f-4daf-948b-ba148c160261)

2024-03-13 16:07 UTC, chinathaip commented
FYI, this issue closes https://github.com/stamford-syntax-club/course-compose/issues/49

2024-03-13 16:28 UTC, chinathaip commented on apps/web/app/signin/page.tsx
> +    const [showRepeatPassword, setShowRepeatPassword] = useState(false);
is this state being referred to anywhere? If not, let's remove it

2024-03-13 16:28 UTC, chinathaip commented on apps/web/app/signin/page.tsx
> +import { useToggle, upperFirst } from '@mantine/hooks';
is `upperFirst` being used to anywhere? If not, let's remove it

2024-03-13 16:28 UTC, chinathaip commented on apps/web/app/signin/page.tsx
> +export default function SigninPage(props: PaperProps) {
I'm a bit confused with this :(

Can you explain why are we passing paper props to this component?

React actually complains about this too

![image](https://github.com/stamford-syntax-club/course-compose/assets/92321280/442a5189-8c8f-4c81-a23d-7560c808a935)

2024-03-14 08:01 UTC, Lxkas requested changes

2024-03-14 08:01 UTC, Lxkas commented on apps/web/app/signin/page.tsx
> +            terms: true,
Are you sure this should default to true?

2024-05-17 11:01 UTC, Lxkas approved these changes
LGTM!

2024-05-17 12:41 UTC, NayHtetKyaw approved these changes
GUDGUD

2024-05-17 13:48 UTC, merged